/// 角色与权限码常量（M1 稳定版）。
pub const ROLE_ADMIN: &str = "admin";

pub const PROJECT_READ: &str = "PROJECT.READ";
pub const PROJECT_WRITE: &str = "PROJECT.WRITE";
pub const ASSET_GATEWAY_READ: &str = "ASSET.GATEWAY.READ";
pub const ASSET_GATEWAY_WRITE: &str = "ASSET.GATEWAY.WRITE";
pub const ASSET_DEVICE_READ: &str = "ASSET.DEVICE.READ";
pub const ASSET_DEVICE_WRITE: &str = "ASSET.DEVICE.WRITE";
pub const ASSET_POINT_READ: &str = "ASSET.POINT.READ";
pub const ASSET_POINT_WRITE: &str = "ASSET.POINT.WRITE";
pub const DATA_REALTIME_READ: &str = "DATA.REALTIME.READ";
pub const DATA_MEASUREMENTS_READ: &str = "DATA.MEASUREMENTS.READ";
pub const CONTROL_COMMAND_ISSUE: &str = "CONTROL.COMMAND.ISSUE";
pub const CONTROL_COMMAND_READ: &str = "CONTROL.COMMAND.READ";
pub const ALARM_RULE_READ: &str = "ALARM.RULE.READ";
pub const ALARM_RULE_WRITE: &str = "ALARM.RULE.WRITE";
pub const ALARM_EVENT_READ: &str = "ALARM.EVENT.READ";

pub const RBAC_USER_READ: &str = "RBAC.USER.READ";
pub const RBAC_USER_WRITE: &str = "RBAC.USER.WRITE";
pub const RBAC_ROLE_READ: &str = "RBAC.ROLE.READ";
pub const RBAC_ROLE_WRITE: &str = "RBAC.ROLE.WRITE";

pub const SYSTEM_METRICS_READ: &str = "SYSTEM.METRICS.READ";

pub const PERMISSION_CODES: [&str; 20] = [
    PROJECT_READ,
    PROJECT_WRITE,
    ASSET_GATEWAY_READ,
    ASSET_GATEWAY_WRITE,
    ASSET_DEVICE_READ,
    ASSET_DEVICE_WRITE,
    ASSET_POINT_READ,
    ASSET_POINT_WRITE,
    DATA_REALTIME_READ,
    DATA_MEASUREMENTS_READ,
    CONTROL_COMMAND_ISSUE,
    CONTROL_COMMAND_READ,
    ALARM_RULE_READ,
    ALARM_RULE_WRITE,
    ALARM_EVENT_READ,
    RBAC_USER_READ,
    RBAC_USER_WRITE,
    RBAC_ROLE_READ,
    RBAC_ROLE_WRITE,
    SYSTEM_METRICS_READ,
];
